### ISSUE TITLE
bug: fix option doesn't account for `~` or `^`

### ISSUE THREAD

**Issue by juliusmarminge** [QuiiBz/sherif#37]
When using the --fix when you have multiple versions, sherif seems to ignore if my version is exact or not

This is the result of changing superjson to 2.1.0 then running `pnpm dlx sherif@latest --fix` and choosing 2.2.0, as you can see, it removed my "preference" to have the version locked:

![CleanShot 2023-11-25 at 18 13 59@2x](https://github.com/QuiiBz/sherif/assets/51714798/c4f69a8d-5e0a-4b84-9ea2-82c217280851)

**Comment by QuiiBz** [comment]
Thanks, definitely not wanted. I'll take a look tomorrow.

**Comment by QuiiBz** [comment]
Fix released in 0.6.1, thanks!
