### ISSUE TITLE
feat?: `--fix` should run install command if fixing version missmatches

### ISSUE THREAD

**Issue by juliusmarminge** [QuiiBz/sherif#38]
when running `--fix` and fixing a version, I believe sherif should also run the install command for the package manager at use:

![CleanShot 2023-11-25 at 18 16 12@2x](https://github.com/QuiiBz/sherif/assets/51714798/9938b30e-7c34-4083-9ce3-7e12f7765c19)

**Comment by QuiiBz** [comment]
Forgot to reply to this, sorry. I'm not 100% convinced about automatically running `<packageManager> install` after autofixing. What if it fails to install, should Sherif revert the changes?

**Comment by Willem-Jaap** [comment]
Maybe a prompt to let the user choose himself?
```
Would you like Sherif to run `pnpm install` (Y/n)
```

**Comment by thomasfr** [comment]
No please don’t run install. Which package manager should it use? And it also complicates the possibility to run `fix` in non-interactive mode as well #68

**Comment by QuiiBz** [comment]
We could add a `--install` flag that when used along `--fix`, also runs the install command of your package manager.

**Comment by thomasfr** [comment]
Ok, @QuiiBz you convinced me that it’s actually a good idea to run install afterwards to update the lockfile as well.

**Comment by QuiiBz** [comment]
Now released in https://github.com/QuiiBz/sherif/releases/tag/v1.0.0!
