### ISSUE TITLE
bug: All paths defined in the workspace should match at least one package

### ISSUE THREAD

**Issue by dinsterizer** [QuiiBz/sherif#43]
```yaml
packages:
  - '@*'
```

My project structure

- @api
- @web
- pnpm-workspace.yaml

pnpm found 2 workspace but sherif found 0

**Comment by QuiiBz** [comment]
Just to make sure: `@api` and `@web` are folders at the root of your monorepo?

**Comment by dinsterizer** [comment]
Yes, I'm sure
![image](https://github.com/QuiiBz/sherif/assets/64189902/12ae410f-c1b5-4630-b14a-7edc20cc7a9e)

**Comment by QuiiBz** [comment]
Released in https://github.com/QuiiBz/sherif/releases/tag/v0.7.0, sorry for the delay!
