### ISSUE TITLE
Wish option to view 'multiple-dependency-versions' as a warning instead of an error.

### ISSUE THREAD

**Issue by sungh0lim** [QuiiBz/sherif#46]
I want to include Sherif in CI, but it's difficult to match versions right away in the project we are transferring. So, I wish there was an option to change items that appear as errors to warnings.

**Comment by QuiiBz** [comment]
Sherif is very opinionated and we don't really want to add a configuration step, even if not mandatory.

While you're updating your dependencies, you can use the `--ignore-rule multiple-dependency-versions` option to ignore entirely the rule, or `--ignore-dependency @dependency/name` to ignore a specific dependency. That should help integrating Sherif in your CI immediately, and enable the rule later when you've fixed all dependencies errors.

Let me know if that would work for you.

**Comment by sungh0lim** [comment]
Rather than ignoring it, I just wanted it to be checked every time in CI with warning option.
Thanks for the reply. We decided to use this for monthly checking rather than putting it in CI.

**Comment by QuiiBz** [comment]
Thanks, I'll close the issue unless more folks are interested in the same feature.
