### ISSUE TITLE
`multiple-dependency-versions` should also includes peer dependencies

### ISSUE THREAD

**Issue by beaussan** [QuiiBz/sherif#49]
In a monorepo where we mark dependencies as external, we can use `peerDependencies` to spesify versions too. The rule doesn't include them in the checks however.

**Comment by QuiiBz** [comment]
Good catch, thanks! Not sure yet when I'll trigger another release, hopefully in January.

**Comment by beaussan** [comment]
Thanks a lot!! I was learning rust to be able to contribute, thanks a lot for the swift response!

**Comment by QuiiBz** [comment]
Released in https://github.com/QuiiBz/sherif/releases/tag/v0.8.0!
