### ISSUE TITLE
Yarn workspace

### ISSUE THREAD

**Issue by exdeniz** [QuiiBz/sherif#53]
Yarn can have another format besides the usual workspace config.

```
// flow type definition:
export type WorkspacesConfig = {
  packages?: Array<string>,
  nohoist?: Array<string>,
};
```

If the config looks like:
```
"workspaces": {
  "packages": ["packages/*"],
  "nohoist": ["**/react-native", "**/react-native/**"]
}
```
Sherif crashes with an error 

```
error Failed to collect packages
Error while parsing "./package.json": invalid type: map, expected a sequence at line 19 column 16
```

**Comment by QuiiBz** [comment]
TIL about this format! Do you know if this format is often used? I've personally never heard of it so I'm curious to know if it's something that should be supported or not (based on its usage).

**Comment by exdeniz** [comment]
Yes, that is the only way to specify nohoist for yarn. Details [here](https://classic.yarnpkg.com/blog/2018/02/15/nohoist/)

Using the format in projects:
<img width="614" alt="image" src="https://github.com/QuiiBz/sherif/assets/682584/a6e7a7de-f606-45be-a42d-bce0c4967c09">
