### ISSUE TITLE
Sherif does not respect prettier config in project

### ISSUE THREAD

**Issue by Willem-Jaap** [QuiiBz/sherif#54]
After fixing errors with `--fix` (which works amazing btw) Sherif applies the changes to the correct package.json's. However in the process does not respect the formatting of prettier.

![image](https://github.com/QuiiBz/sherif/assets/67187467/bb1856d4-8cf8-4db7-ae37-4f0d2ac78384)

**Comment by QuiiBz** [comment]
Good catch, however that looks like a complex problem. We parse the file as JSON, update it and write it back to disk, but without preserving the indentation. I'm not sure if this is easily fixable but will take a look.

**Comment by QuiiBz** [comment]
Released in https://github.com/QuiiBz/sherif/releases/tag/v0.8.0!

**Comment by Willem-Jaap** [comment]
Nice work, thanks!
