### ISSUE TITLE
Not working on my repo

### ISSUE THREAD

**Issue by programad** [QuiiBz/sherif#70]
Hey! Great tool you have there, congratulations!

Unfortunately, I could not run it on my repo at https://github.com/rocketclimb/rocketicons

It gives me this error:

`
could not determine executable to run
`

Here is the complete log:

0 verbose cli /opt/homebrew/Cellar/node/22.0.0/bin/node /opt/homebrew/lib/node_modules/npm/bin/npm-cli.js
1 info using npm@10.5.1
2 info using node@v22.0.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/opt/homebrew/lib/node_modules/npm/npmrc Completed in 0ms
6 timing config:load:builtin Completed in 0ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/Users/programad/dev/rocketclimb/rocketicons/.npmrc Completed in 0ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:/Users/programad/.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/opt/homebrew/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 0ms
16 timing config:load Completed in 4ms
17 timing npm:load:configload Completed in 4ms
18 timing config:load:flatten Completed in 1ms
19 timing npm:load:mkdirpcache Completed in 0ms
20 timing npm:load:mkdirplogs Completed in 0ms
21 verbose title npm exec sheriff@latest
22 verbose argv "exec" "--" "sheriff@latest"
23 timing npm:load:setTitle Completed in 2ms
24 timing npm:load:display Completed in 1ms
25 verbose logfile logs-max:10 dir:/Users/programad/.npm/_logs/2024-06-29T14_24_48_067Z-
26 verbose logfile /Users/programad/.npm/_logs/2024-06-29T14_24_48_067Z-debug-0.log
27 timing npm:load:logFile Completed in 3ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 16ms
31 silly logfile start cleaning logs, removing 1 files
32 silly logfile done cleaning log files
33 timing arborist:ctor Completed in 0ms
34 verbose shrinkwrap failed to load node_modules/.package-lock.json out of date, updated: packages/ignition
35 http fetch GET 200 https://registry.npmjs.org/sheriff 103ms (cache revalidated)
36 timing command:exec Completed in 561ms
37 verbose stack Error: could not determine executable to run
37 verbose stack     at getBinFromManifest (/opt/homebrew/lib/node_modules/npm/node_modules/libnpmexec/lib/get-bin-from-manifest.js:17:23)
37 verbose stack     at exec (/opt/homebrew/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:188:15)
37 verbose stack     at async module.exports (/opt/homebrew/lib/node_modules/npm/lib/cli-entry.js:61:5)
38 verbose pkgid sheriff@0.0.2
39 verbose cwd /Users/programad/dev/rocketclimb/rocketicons
40 verbose Darwin 23.5.0
41 verbose node v22.0.0
42 verbose npm  v10.5.1
43 error could not determine executable to run
44 verbose exit 1
45 timing npm Completed in 658ms
46 verbose code 1
47 error A complete log of this run can be found in: /Users/programad/.npm/_logs/2024-06-29T14_24_48_067Z-debug-0.log

**Comment by QuiiBz** [comment]
Looking at the logs, it looks like you wrote `npm exec sheriff@latest` instead of `npm exec sherif@latest` (notice `sheriff` with two `ff`, but the package name only has a single `f` as `sherif`).
