### ISSUE TITLE
Customizable rule severity

### ISSUE THREAD

**Issue by DaniFoldi** [QuiiBz/sherif#73]
Hi :wave:,

I saw your tweet and gave sherif a go on a few different repositories. One rule that constantly triggered errors was `multiple-dependency-versions`. Large monorepos may require different versions of typescript, for example. Some packages like expo have a very strong opinion about the version of typescript they are compatible with, while others are updated, naturally.

It would be nice if rules had a way to change their severity, so large monorepos wouldn't break in CI.

**Comment by QuiiBz** [comment]
Thanks for trying Sherif - indeed, this tool is opinionated and zero-config which is why we don't allow to customize rule levels. However, for cases such as the one you described, you can ignore a specific dependency from this rule: [see the docs](https://github.com/QuiiBz/sherif#multiple-dependency-versions-)

```bash
sherif --ignore-dependency typescript
```

If you want, you can also completely disable the `multiple-dependency-versions` rule if it doesn't provide any value for you:

```
sherif -ignore-rule multiple-dependency-versions
```

Does that help?

**Comment by DaniFoldi** [comment]
Thanks for the quick response!

I saw the --ignore-rule option, and it's probably what we are going to have to use in order to adopt sherif. I understand that zero-config means that some settings cannot be changed, even if that means we lose out on warnings which devs may manually attend to.

I'm happy to close this issue if you feel adding a `--warning/--error <rule>` flag is out of scope.

**Comment by QuiiBz** [comment]
Unless more folks are interested in this feature, I don't think it's worth it for now. Happy to revisit my decision later if more folks are asking for it though!

**Comment by mhpaler** [comment]
@QuiiBz I'll put my vote in for this!

Came looking to see if sherif could be configured for just this type of thing...alas, it's not possible.

Something like this would be ideal:

```
    "lint:repo": "sherif --warning multiple-dependency-versions"
```



Happy to provide more details of my use case if that helps...

**Comment by simon-v-swyftx** [comment]
Hey yep I was looking for a way to bump `packages-without-package-json` from a warning to an error
