### ISSUE TITLE
`--fix` should not modify nonaffected packages 

### ISSUE THREAD

**Issue by jqpe** [QuiiBz/sherif#74]
https://github.com/QuiiBz/sherif/assets/65775308/5edf809e-9e96-4046-8845-c494078d4d59

<img width="1037" alt="VSCode" src="https://github.com/QuiiBz/sherif/assets/65775308/c976826a-5ce2-4ba3-b7e9-90ae7bcb773c">

<img width="1044" alt="VSCode" src="https://github.com/QuiiBz/sherif/assets/65775308/45ced97a-7179-4e53-ba03-669d22bda0f4">

Currently sherif will modify all packages with a fixed dependency, even if the dependency hasn't changed. It will not affect packages without the fixed dependency. As seen on the above demo, sherif will remove line breaks from all resolved packages.

[Reproduction](https://github.com/jqpe/sherif-repro)

Easiest solution is to probably not write to the nonaffected package at all, which should also improve performance by a little. Ideally the tool would also keep line breaks on modified packages.

**Comment by QuiiBz** [comment]
I've been wanting to add this for a while, thanks for the reminder! I'll release a new version later this weekend.
