### ISSUE TITLE
Allow specifying multiple wildcards in workspaces

### ISSUE THREAD

**Issue by thesobercoder** [QuiiBz/sherif#88]
I have a PNPM workspace where I use wildcard to map child package directories, and for some reason sherif is flagging that as an error.

![image](https://github.com/user-attachments/assets/e1027f6e-835d-45d0-8637-de95cec570e9)

**Comment by QuiiBz** [comment]
Sherif only supports a single level of wildcard right now (e.g. `packages/*`), definitely something we should improve.

**Comment by QuiiBz** [comment]
I've just merged https://github.com/QuiiBz/sherif/pull/92 which adds support for one level of `**` - will trigger a new release in the next few days.

**Comment by QuiiBz** [comment]
Now released in https://github.com/QuiiBz/sherif/releases/tag/v1.0.0!

**Comment by thesobercoder** [comment]
@QuiiBz Thanks for the release. I tested in my monorepo. The only issue that I see is that it doesn't respect the packages excluded in a PNPM workspace, i.e. packages that are marked with `!packages/exclude/**`

**Comment by QuiiBz** [comment]
That's right, ignored packages do not support it yet, there will be a follow-up PR soon.
