### ISSUE TITLE
Adding !<package> will make all the child folders ignored by sherif

### ISSUE THREAD

**Issue by baptisteArno** [QuiiBz/sherif#90]
This behavior is expected, as any folder in e.g. `apps/*` is considered a package. We could (and maybe should) ignore `.npm` folders though, and for `packages/ui` you should update your `workspaces` configuration to add `!packages/ui`

_Originally posted by @QuiiBz in https://github.com/QuiiBz/sherif/issues/86#issuecomment-2283258838_
         
On my repo: https://github.com/baptisteArno/typebot.io

If I run sherif as is, it will say that openai package has different versions accross the repo.

As soon as I add !packages/forge to my package json workspaces list, the error disappear which makes me think that forge/blocks/openai package is then ignored because of that

**Comment by QuiiBz** [comment]
Now released in https://github.com/QuiiBz/sherif/releases/tag/v1.0.0!
