### ISSUE TITLE
thread 'main' panicked at src/rules/non_existant_packages.rs:138:26:

### ISSUE THREAD

**Issue by jellydn** [QuiiBz/sherif#95]
Hi @QuiiBz,

Thank you for your great work. I saw your post on x.com about v1 release. I wanted to give a try on my monorepo and got below error.

```sh
bunx sherif --fix --no-install
thread 'main' panicked at src/rules/non_existant_packages.rs:138:26:
called `Option::unwrap()` on a `None` value
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I guess something is related with `--no-install`.

**Comment by QuiiBz** [comment]
This looks unrelated to any recent release. Could you share a link or minimal reproduction of your monorepo? It looks like you don't have any `pnpm-workspace.yaml` nor `workspaces` field configured.

**Comment by jellydn** [comment]
> It looks like you don't have any pnpm-workspace.yaml nor workspaces field configured.

I don't think so. I could see this error if that's not under monorepo.

```sh
❯ bunx sherif --fix --no-install

 ⨯ error Failed to collect packages
   No `workspaces` field in the root `package.json`, or `pnpm-workspace.yaml` file not found in "."
```

> Could you share a link or minimal reproduction of your monorepo? 

Sure, I will try to set up a reproduction repo. I am using `turborepo + yarn` on my project.

**Comment by QuiiBz** [comment]
Hey! I've tried many different things to reproduce the issue, but no luck so far.

**Comment by jellydn** [comment]
Hi @QuiiBz Sorry, I forgot this one. I tried your tool on my project but it's under private repository which contains multi packages/apps (nodejs/.net/react/nextjs) + git submodule. I am not sure which one cause the issue yet.

**Comment by jellydn** [comment]
I guess something wrong with `bunx` as It's working for me with the below command.

```sh
❯ pnpm dlx sherif@latest --fix --no-install
```

**Comment by spanning-code** [comment]
pls reopen

❯ npx sherif@latest --fix --no-install
thread 'main' panicked at src/rules/non_existant_packages.rs:138:26:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
(base)

**Comment by QuiiBz** [comment]
Can you share a reproduction? I've been unable to reproduce the issue.
