### ISSUE TITLE
`yarn.lock` taking precedence over `bun.lockdb`

### ISSUE THREAD

**Issue by baptisteArno** [QuiiBz/sherif#97]
With bun you can also create a yarn.lock file (https://bun.sh/docs/install/lockfile)

If Sherif detects a yarn.lock file then it thinks we are using yarn pm.

https://github.com/QuiiBz/sherif/blob/14a2ad4fa006dc4e2d8f9519364afe351de7266e/src/install.rs#L18-L28

A quick fix would be to check for bun lockfile before yarn? Would that work for you? If so, I can create a PR

**Comment by QuiiBz** [comment]
TIL that Bun can generates `yarn.lock` files; the fix sounds good to me!

**Comment by QuiiBz** [comment]
Released in [1.0.1](https://github.com/QuiiBz/sherif/releases/tag/v1.0.1), thanks!
